name: Direct RDP Access with Cloudflare Tunnel

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    env:
      # يجب إنشاء سر في GitHub باسم CLOUDFLARED_HOSTNAME يحتوي على اسم النطاق المُهيأ (مثلاً: rdp.example.com)
      CLOUDFLARED_HOSTNAME: ${{ secrets.CLOUDFLARED_HOSTNAME }}

    steps:
      - name: Enable Remote Desktop and Configure Firewall
        run: |
          # تمكين Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # تفعيل قواعد جدار الحماية الخاصة بـ Remote Desktop
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # تمكين المصادقة عبر الشبكة (NLA)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          # تعيين كلمة مرور للمستخدم المحلي
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Download Cloudflared
        run: |
          Invoke-WebRequest "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile cloudflared.exe

      - name: Create Cloudflare Tunnel Credentials File
        env:
          # يجب إنشاء سر في GitHub باسم CLOUDFLARED_CREDENTIALS يحتوي على محتوى ملف بيانات الاعتماد الذي تحصل عليه من Cloudflare
          CLOUDFLARED_CREDENTIALS: ${{ secrets.CLOUDFLARED_CREDENTIALS }}
        run: |
          echo "$env:CLOUDFLARED_CREDENTIALS" | Out-File -Encoding ascii cloudflared.json

      - name: Create Cloudflare Tunnel Config File
        run: |
          @"
          tunnel: mytunnel
          credentials-file: cloudflared.json
          ingress:
            - hostname: $env:CLOUDFLARED_HOSTNAME
              service: tcp://localhost:3389
            - service: http_status:404
          "@ | Out-File -Encoding ascii config.yml

      - name: Start Cloudflare Tunnel for RDP
        run: .\cloudflared.exe tunnel --config config.yml run

      - name: Wait for 2147483 seconds
        run: Start-Sleep -Seconds 2147483
