name: Direct RDP Access

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Enable Remote Desktop and Configure Firewall
        run: |
          # تمكين Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # تفعيل قواعد جدار الحماية الخاصة بـ Remote Desktop
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # تمكين المصادقة عبر الشبكة (NLA)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          # تعيين كلمة مرور للمستخدم المحلي (تأكد من وجود المستخدم runneradmin)
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Retrieve and Output Public IP
        run: |
          $publicIP = Invoke-RestMethod -Uri "https://api.ipify.org"
          Write-Output "Public IP: $publicIP"
