name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Cloudflare Tunnel
      run: |
        Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Authenticate and Start Tunnel
      run: |
        .\cloudflared.exe tunnel --url rdp://localhost:3389 --log-level debug > tunnel.log 2>&1 &
        Start-Sleep -Seconds 10
        Get-Content tunnel.log | Select-String -Pattern "https://.*trycloudflare.com" | ForEach-Object { $_.Matches.Value } | Out-File -Encoding utf8 tunnel_url.txt

    - name: Print Cloudflare RDP URL
      run: Get-Content tunnel_url.txt
