version: '3'
services:
  rtmp-stream:
    image: jrottenberg/ffmpeg
    command: >
      ffmpeg -i "http://newlife3.wanicelife.com:8880/live/29us031901/adsf3rdsdc/2140.ts" -c:v libx264 -c:a aac -f flv 
      "rtmp://live.restream.io/live/re_6196730_event3d1f1cd78c7b46bdbd211914261dd5ec"
    restart: always
