version: '3'
services:
  url_checker:
    image: curlimages/curl
    command: >
      curl --head --silent --fail "http://newlife3.wanicelife.com:8880/live/29us031901/adsf3rdsdc/2140.ts" || echo "الرابط غير متاح"
